/*
 * FATformat generated by samtools/ bedtools/Picard(genome.fa.fai file)
 */
package ExomeSeqAnalysisPipe.clusterFeatureGenerated;

/**
 *
 * @author ZHAO Qi
 * @date 2014-2-28 10:40:05
 * @version 1.6.0
 */
public class FAIterm {

    private String Chr;//chromosome name 
    private int length;//chromosome length 
    protected int startChrNum;//offset of the first base of the chromosome sequence in the file 
    protected int seqLineLenth;//length of the fasta lines 
    private int line_blen;

    public FAIterm(String Chr, int length, int startChrNum, int seqLineLenth, int line_blen) {
        this.Chr = Chr;
        this.length = length;
        this.startChrNum = startChrNum;
        this.seqLineLenth = seqLineLenth;
        this.line_blen = line_blen;
    }

    
    
    
    /**
     * Get the value of line_blen
     *
     * @return the value of line_blen
     */
    public int getLine_blen() {
        return line_blen;
    }

    /**
     * Set the value of line_blen
     *
     * @param line_blen new value of line_blen
     */
    public void setLine_blen(int line_blen) {
        this.line_blen = line_blen;
    }

    /**
     * Get the value of seqLineLenth
     *
     * @return the value of seqLineLenth
     */
    public int getSeqLineLenth() {
        return seqLineLenth;
    }

    /**
     * Set the value of seqLineLenth
     *
     * @param seqLineLenth new value of seqLineLenth
     */
    public void setSeqLineLenth(int seqLineLenth) {
        this.seqLineLenth = seqLineLenth;
    }


    /**
     * Get the value of startChrNum
     *
     * @return the value of startChrNum
     */
    public int getStartChrNum() {
        return startChrNum;
    }

    /**
     * Set the value of startChrNum
     *
     * @param startChrNum new value of startChrNum
     */
    public void setStartChrNum(int startChrNum) {
        this.startChrNum = startChrNum;
    }


    /**
     * Get the value of length
     *
     * @return the value of length
     */
    public int getLength() {
        return length;
    }

    /**
     * Set the value of length
     *
     * @param length new value of length
     */
    public void setLength(int length) {
        this.length = length;
    }


    /**
     * Get the value of Chr
     *
     * @return the value of Chr
     */
    public String getChr() {
        return Chr;
    }

    /**
     * Set the value of Chr
     *
     * @param Chr new value of Chr
     */
    public void setChr(String Chr) {
        this.Chr = Chr;
    }

}
